# Generated by Django 5.1.2 on 2024-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip',
            field=models.TextField(blank=True),
        ),
    ]
