# Generated by Django 5.1.2 on 2024-11-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.shippingaddress'),
        ),
    ]
