# Generated by Django 5.1.2 on 2024-11-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_bid_carddetails_collection_paypaldetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_icon',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
