# Generated by Django 5.1.2 on 2024-11-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shippingaddress_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold'), ('E', 'Expired')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
