# Generated by Django 5.1.2 on 2024-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_availability_alter_item_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Shipped'), ('R', 'Received')], default='P', max_length=1),
        ),
    ]
