# Generated by Django 5.1.2 on 2024-11-14 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_balance_alter_account_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='api.profile'),
        ),
    ]
