# Generated by Django 5.1.2 on 2024-11-23 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='carrier',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='estimated_delivery',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='in', max_length=2)),
                ('weight_unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'kilograms')], default='lb', max_length=2)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
