# Generated by Django 5.1.2 on 2024-11-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_carrier_transaction_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='asking_price',
            new_name='selling_price',
        ),
    ]
