# Generated by Django 5.1.2 on 2024-11-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_bids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
