# Generated by Django 5.1.2 on 2024-11-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rating_ratee_alter_rating_rater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='suspension_fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='suspension_strikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
