# Generated by Django 5.1.2 on 2024-11-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_total_bids_alter_item_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold')], default='A', max_length=1),
        ),
    ]
