# Generated by Django 5.1.2 on 2024-11-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_report_status_quitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='winner_status',
            field=models.CharField(choices=[('I', 'Ineligible'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='I', max_length=1),
        ),
    ]
