# Generated by Django 5.1.2 on 2024-11-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_save_profile_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
