# Generated by Django 5.1.2 on 2024-11-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_account_points_bid_winner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='maximum_bid',
            field=models.DecimalField(decimal_places=2, default=1000000.0, help_text='Maximum bid amount allowed', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_bid',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum bid amount allowed', max_digits=10),
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('captcha_completed', models.BooleanField(default=False)),
                ('time_of_application', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
