# Generated by Django 5.1.2 on 2024-11-17 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_item_image_remove_item_slug_item_image_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_of_comment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_comment',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
