# Generated by Django 5.1.2 on 2024-11-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment_date_of_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='selling_price',
            new_name='asking_price',
        ),
    ]
