# Generated by Django 5.1.2 on 2024-11-17 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_selling_price_item_asking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winning_bid',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_item', to='api.bid'),
        ),
    ]
